#-------------------------------
# Site Settings
title: Shubhashis Roy Dipta Blog
logo: # You can add own logo. For example '/images/logo.png'.
description: A blog on Machine Learning, NLP, Vision, Multimodal AI
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dipta007.github.io" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author:
  name: Shubhashis Roy Dipta
  bio: A PhD student at the University of Maryland, Baltimore County, USA. I am working on Machine Learning, NLP, Vision, Multimodal AI.
  avatar: '/images/avatar.jpg'
  url: https://roydipta.com/?utm_source=blog.roydipta.com&utm_medium=header

social:
- {icon: "ion-logo-linkedin", link: "https://linkedin.com/in/iamdipta007"}
- {icon: "ion-logo-github", link: "https://github.com/dipta007"}
- {icon: "ion-logo-twitter", link: "https://twitter.com/iamdipta007"}
- {icon: "ion-logo-youtube", link: "https://youtube.com/@RoyDipta"}
- {icon: "ion-logo-facebook", link: "https://facebook.com/iamdipta007"}
- {icon: "ion-logo-instagram", link: "https://instagram.com/iamdipta007"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true 
  hero__title: Hey, I’m Shubhashis Roy Dipta
  hero__description: I write about Machine Learning, NLP, Vision, Multimodal AI
  hero__image: '/images/hero.jpeg'


#-------------------------------
# Newsletter
mailchimp: 
  enable: true
  identifier: roydipta.us21.list-manage.com/subscribe/post?u=d959ff3473bc4ddf834bf8fbe&amp;id=ccd3f0e7a2&amp;f_id=00e9f3e6f0
  input__text: Subscribe here
  button__text: Get a new tip


#-------------------------------
# Gallery Footer Section
gallery:
  enable: False
  gallery__title: Gallery
  gallery__columns: 3
  gallery__images:
    - alt: 'Rest'
      url: '/images/100.jpg'
    - alt: 'Lifestyle'
      url: '/images/101.jpg'
    - alt: 'Hobby'
      url: '/images/102.jpg'
    - alt: 'Notes'
      url: '/images/103.jpg'
    - alt: 'Rest'
      url: '/images/104.jpg'
    - alt: 'Hobby'
      url: '/images/105.jpg'
    - alt: 'Fashion'
      url: '/images/106.jpg'
    - alt: 'Notes'
      url: '/images/107.jpg'
    - alt: 'Rest'
      url: '/images/108.jpg'


#-------------------------------
# Contact Settings
contact:
  email: iamdipta@gmail.com # Add your email for contant form
  description: I am a PhD student at the University of Maryland, Baltimore County, USA. I am working on Machine Learning, NLP, Vision, Multimodal AI. To contact me, please fill out the form below.

# NOTE
# Menca theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
comments:
  active: 'giscus' # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: dipta007/giscus-srd # <gh-username>/<repo>
    repo_id: R_kgDOLHLfzw
    category: blog.roydipta.com
    category_id: DIC_kwDOLHLfz84CcxRZ
    mapping: url # optional, default to 'pathname'
    input_position: top # optional, default to 'bottom'
    lang: en # optional, default to the value of `site.lang`
    reactions_enabled: 1 # optional, default to the value of `1`


#-------------------------------
# Google Analytics
google-analytics: G-8L0137QP32 # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed